//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTab.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ColumnEffect
    {
        public ColumnEffect()
        {
            this.ColumnInfos = new HashSet<ColumnInfo>();
        }
    
        public int EffectID { get; set; }
        public string Effect { get; set; }
    
        public virtual ICollection<ColumnInfo> ColumnInfos { get; set; }
    }
}
