//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTab.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ColumnInfo
    {
        public ColumnInfo()
        {
            this.TableItems = new HashSet<TableItem>();
        }
    
        public string ColumnName { get; set; }
        public int ColumnOrder { get; set; }
        public int ColumnEffect { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ColumnEffect ColumnEffect1 { get; set; }
        public virtual ICollection<TableItem> TableItems { get; set; }
    }
}
