//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTab.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableItem
    {
        public System.DateTime ItemDate { get; set; }
        public string ColumnName { get; set; }
        public string Note { get; set; }
        public decimal ItemValue { get; set; }
    
        public virtual ColumnInfo ColumnInfo { get; set; }
    }
}
