//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTab.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class webtabProjectEntities : DbContext
    {
        public webtabProjectEntities()
            : base("name=webtabProjectEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ColumnEffect> ColumnEffects { get; set; }
        public virtual DbSet<ColumnInfo> ColumnInfoes { get; set; }
        public virtual DbSet<TableItem> TableItems { get; set; }
    }
}
